apiVersion: v1
kind: Service
metadata:
  name: {{ include "lockmgr.headlessServiceName" . }}
  labels:
    {{- include "lockmgr.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.regionPort }}
      targetPort: region
      protocol: TCP
      name: region
  selector:
    {{- include "lockmgr.selectorLabels" . | nindent 4 }}
