{{- range .Values.regions }}
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: lockmgr-mtls
  namespace: {{ .namespace }}
  labels:
    {{- include "lockmgr-istio.labels" $ | nindent 4 }}
spec:
  mtls:
    mode: {{ $.Values.peerAuthentication.mtls.mode }}
{{- end }}
