# Copyright (c) 2026 Bob Hablutzel. All rights reserved.
#
# Licensed under a dual-license model: freely available for non-commercial use;
# commercial use requires a separate license. See LICENSE file for details.
# Contact license@gaestalt.com for commercial licensing.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "address.fullname" . }}
  labels:
    {{- include "address.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "address.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "address.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.grpcPort }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.service.httpPort }}
              protocol: TCP
          env:
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.javaOpts | quote }}
            - name: USPS_BASE_URL
              value: {{ .Values.usps.baseUrl | quote }}
            - name: USPS_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: USPS_CLIENT_ID
            - name: USPS_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: USPS_CLIENT_SECRET
            - name: SMARTY_AUTH_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: SMARTY_AUTH_ID
            - name: SMARTY_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: SMARTY_AUTH_TOKEN
            - name: SMARTY_US_STREET_BASE_URL
              value: {{ .Values.smarty.usStreetBaseUrl | quote }}
            - name: SMARTY_INTERNATIONAL_BASE_URL
              value: {{ .Values.smarty.internationalBaseUrl | quote }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
